val friends = sc.textFile("friends.txt").map(x => (x.split("\t")(0).toLong, x.split("\t")(1).toLong))
val friends_rev = friends.map(x => (x._2, x._1))
val friends_lr = friends.union(friends_rev)
val mutualfriends = friends_lr.map(x => (x,1)).reduceByKey((a,b) => a+b).filter(x => x._2 > 1).map(x => x._1).filter(x => x._1 < x._2)
mutualfriends.saveAsTextFile("mutualfriends")